from django.conf.urls.static import static
from myprj.settings import MEDIA_ROOT
from os import name
from django.conf.urls import url
from django.views.static import serve
from django.conf import settings
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="index"),
    path('login',views.login,name="login"),
    path('signup',views.signup,name="signup"),
    path('delete/<int:id>',views.delete,name="delete"),
    path('contact',views.contact_form,name="contact"),
    path('apply/<int:vol_id>/<int:job_id>',views.application,name="apply"),
    path('upload/<int:id>',views.upload,name="upload"),
    path('logout',views.logout_user,name="logout"),
    # home
    path('home',views.home_page,name="home"),
    path('login_home',views.home_login,name="login_home"),
    path('signup_home',views.do_home_signup,name="signup_home"),
    path('profile_home/<int:id>',views.home_profile,name="profile_home"),
    path('home_edit/<int:id>',views.home_edit,name="home_edit"),
    path('home_update/<int:id>',views.home_update,name="home_update"),
    path('search_shopkeeper/<int:id>',views.search_shopkeeper,name="search_shopkeeper"),
    path('shopkeepersearch/<int:id>',views.shopkeepersearch,name="shopkeepersearch"),
    path('Request/<int:home_id>/<int:shop_id>', views.Request, name = 'Request'),
    path('ShopKeepers/<int:home_id>', views.ShopKeepers, name = 'ShopKeepers'),
    # shopkeeper
    path('shopkeeper',views.shopkeeper_home,name="shopkeeper"),
    path('signup_shopkeeper',views.do_shopkeeper_signup,name="signup_shopkeeper"),
    path('login_shopkeeper',views.shopkeeper_login,name="login_shopkeeper"),
    path('profile_shopkeeper/<int:id>',views.shopkeeper_profile,name="profile_shopkeeper"),
    path('search_garbagecollector/<int:id>',views.search_garbagecollector,name="search_garbagecollector"),
    path('garbagecollectorsearch/<int:id>',views.garbagecollectorsearch,name="garbagecollectorsearch"),
    path('vacancy_shop/<int:id>',views.vacancy_shop,name="vacancy_shop"),
    path('Requests_view/<int:id>', views.Requests_view,name="Requests_view"),
    path('accept_req/<int:id>', views.accept_req,name="accept_req"),
    path('decline_req/<int:id>', views.decline_req,name="decline_req"),
    path('Request_shop/<int:shop_id>/<int:gar_id>', views.Request_shop, name = 'Request_shop'),
    path('GarbageCollectors/<int:shop_id>', views.GarbageCollectors, name = 'GarbageCollectors'),
    path('View_application_shop/<int:id>',views.application_shop,name="View_application_shop"),
    path('Houses_list/<int:id>',views.Houses_list,name="Houses_list"),
    path('add_shop/<int:vol_id>/<int:shop>',views.add_shop,name="add_shop"),
    path('assign_home/<int:h>/<int:shop>',views.assign_home,name="assign_home"),
    path('change_vol/<int:id>',views.change_vol,name="change_vol"),
    path('shop_edit/<int:id>',views.shop_edit,name="shop_edit"),
    path('shop_update/<int:id>',views.shop_update,name="shop_update"),
    path('decline_shop/<int:vol_id>/<int:shop>',views.decline_shop,name="decline_shop"),
    # garbage
    path('garbagecollector',views.garbagecollector_home,name="garbagecollector"),
    path('signup_garbagecollector',views.do_garbagecollecter_signup,name="signup_garbagecollector"),
    path('login_garbagecollector',views.garbagecollector_login,name="login_garbagecollector"),
    path('profile_garbagecollector/<int:id>',views.garbagecollector_profile,name="profile_garbagecollector"),
    path('search_company/<int:id>',views.search_company,name="search_company"),
    path('companysearch/<int:id>',views.companysearch,name="companysearch"),
    path('vacancy_garbagecollector/<int:id>',views.vacancy_garbagecollector,name="vacancy_garbagecollector"),
    path('Requests_view_shop/<int:id>', views.Requests_view_shop,name="Requests_view_shop"),
    path('accept_req_shop/<int:id>', views.accept_req_shop,name="accept_req_shop"),
    path('decline_req_shop/<int:id>', views.decline_req_shop,name="decline_req_shop"),
    path('Request_gar/<int:gar_id>/<int:com_id>', views.Request_gar, name = 'Request_gar'),
    path('Company/<int:gar_id>', views.Company, name = 'Company'),
    path('View_application_gar/<int:id>',views.application_gar,name="View_application_gar"),
    path('Shops_list/<int:id>',views.Shops_list,name="Shops_list"),
    path('add_gar/<int:vol_id>/<int:shop>',views.add_gar,name="add_gar"),
    path('assign_shop/<int:h>/<int:shop>',views.assign_shop,name="assign_shop"),
    path('change_vol_gar/<int:id>',views.change_vol_gar,name="change_vol_gar"),
    path('gar_edit/<int:id>',views.gar_edit,name="gar_edit"),
    path('gar_update/<int:id>',views.gar_update,name="gar_update"),
    path('decline_gar/<int:vol_id>/<int:shop>',views.decline_gar,name="decline_gar"),
    # company
    path('company',views.company_home,name="company"),
    path('signup_company',views.do_company_signup,name="signup_company"),
    path('login_company',views.company_login,name="login_company"),
    path('profile_company/<int:id>',views.company_profile,name="profile_company"),
    path('vacancy_company/<int:id>',views.vacancy_company,name="vacancy_company"),
    path('Requests_view_gar/<int:id>', views.Requests_view_gar,name="Requests_view_gar"),
    path('accept_req_gar/<int:id>', views.accept_req_gar,name="accept_req_gar"),
    path('decline_req_gar/<int:id>', views.decline_req_gar,name="decline_req_gar"),
    path('View_application_com/<int:id>',views.application_com,name="View_application_com"),
    path('Gar_list/<int:id>',views.Gar_list,name="Gar_list"),
    path('add_gar/<int:vol_id>/<int:shop>',views.add_gar,name="add_gar"),
    path('assign_gar/<int:h>/<int:shop>',views.assign_gar,name="assign_gar"),
    path('change_vol_com/<int:id>',views.change_vol_com,name="change_vol_com"),
    path('add_com/<int:vol_id>/<int:shop>',views.add_com,name="add_com"),
    path('com_edit/<int:id>',views.com_edit,name="com_edit"),
    path('com_update/<int:id>',views.com_update,name="com_update"),
    path('decline_com/<int:vol_id>/<int:shop>',views.decline_com,name="decline_com"),
    # volunteer
    path('volunteer',views.volunteer_home,name="volunteer"),
    path('signup_volunteer',views.do_volunteer_signup,name="signup_volunteer"),
    path('login_volunteer',views.volunteer_login,name="login_volunteer"),
    path('profile_volunteer/<int:id>',views.volunteer_profile,name="profile_volunteer"),
    path('hiring_offers/<int:id>',views.jobopp,name="hiring_offers"),
    path('List_home/<int:id>',views.home_list,name="home_list"), 
    path('home_collect/<int:id>',views.home_collect,name="home_collect"),
    path('shop_collect/<int:id>',views.shop_collect,name="shop_collect"),
    path('gar_collect/<int:id>',views.gar_collect,name="gar_collect"),
    path('vol_edit/<int:id>',views.vol_edit,name="vol_edit"),
    path('vol_update/<int:id>',views.vol_update,name="vol_update"),
   
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)