# Generated by Django 3.2.5 on 2021-09-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='garbagecollecter',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='home',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='shopkeeper',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='admin',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
