# Generated by Django 3.2.5 on 2021-09-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210907_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=224, verbose_name='Your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('message', models.TextField(verbose_name='Your Message or Query')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('F', 'Farms or Nurserys'), ('C', 'Company'), ('O', 'Others')], default=1, max_length=225),
        ),
    ]
