# Generated by Django 3.2.5 on 2021-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210911_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=224, verbose_name='Your Name')),
                ('job_title', models.CharField(max_length=224, verbose_name='Job Title')),
                ('job_description', models.TextField(verbose_name='Job Dexcrition')),
            ],
        ),
    ]
