# Generated by Django 3.2.5 on 2021-09-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopvol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ManyToManyField(to='my_app.home')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='garvol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ManyToManyField(to='my_app.shopkeeper')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='comvol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ManyToManyField(to='my_app.garbagecollecter')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer')),
            ],
        ),
    ]
