# Generated by Django 3.2.5 on 2021-09-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_vacancy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req_status', models.IntegerField(default=0)),
                ('home_owner_name', models.CharField(max_length=50)),
                ('req_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.home')),
                ('req_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.shopkeeper')),
            ],
        ),
    ]
