# Generated by Django 3.2.5 on 2021-09-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_requests_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests_s',
            old_name='home_owner_name',
            new_name='shop_owner_name',
        ),
    ]
