# Generated by Django 3.2.5 on 2021-09-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_rename_home_owner_name_requests_s_shop_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests_G',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req_status', models.IntegerField(default=0)),
                ('shop_owner_name', models.CharField(max_length=50)),
                ('req_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.garbagecollecter')),
                ('req_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.company')),
            ],
        ),
    ]
