# Generated by Django 3.2.5 on 2021-09-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_requests_g'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests_g',
            old_name='shop_owner_name',
            new_name='gar_owner_name',
        ),
    ]
