# Generated by Django 3.2.5 on 2021-09-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20210913_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.CharField(choices=[('Shopkeeper', 'Shopkeeper'), ('GarabgeCollector', 'GarbageCollector'), ('Company', 'Company')], default='Shopkeeper', max_length=200),
        ),
    ]
