# Generated by Django 3.2.5 on 2021-09-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_vacancy_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='form',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_description',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='documents/')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.vacancy')),
                ('vol_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer')),
            ],
        ),
    ]
