# Generated by Django 3.2.5 on 2021-09-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_auto_20210913_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='vol_details',
        ),
        migrations.AddField(
            model_name='apply',
            name='vol_address',
            field=models.CharField(default='Address', max_length=200, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='apply',
            name='vol_email',
            field=models.EmailField(default='Email', max_length=254, verbose_name='Your Email'),
        ),
        migrations.AddField(
            model_name='apply',
            name='vol_name',
            field=models.CharField(default='Name', max_length=100, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='apply',
            name='vol_phone',
            field=models.CharField(default='Phone Number', max_length=100, verbose_name='Your Phone'),
        ),
    ]
