# Generated by Django 3.2.5 on 2021-09-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_auto_20210913_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='upload',
            field=models.FileField(upload_to='media'),
        ),
    ]
