# Generated by Django 3.2.5 on 2021-09-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_alter_apply_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
