# Generated by Django 3.2.5 on 2021-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_alter_home_garbage_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='garbage_collected',
            field=models.IntegerField(),
        ),
    ]
