# Generated by Django 3.2.5 on 2021-09-14 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_alter_home_garbage_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='volunteers',
            field=models.ManyToManyField(to='my_app.volunteer'),
        ),
        migrations.CreateModel(
            name='Acceptance_s',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('req_status', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.vacancy')),
                ('req_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer')),
                ('req_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.shopkeeper')),
            ],
        ),
    ]
