# Generated by Django 3.2.5 on 2021-09-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_auto_20210914_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='vol_address',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='vol_email',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='vol_name',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='vol_phone',
        ),
        migrations.AddField(
            model_name='apply',
            name='vol',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer'),
        ),
    ]
