# Generated by Django 3.2.5 on 2021-09-14 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_auto_20210914_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='vol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer'),
        ),
    ]
