# Generated by Django 3.2.5 on 2021-09-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_alter_apply_vol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apply',
        ),
    ]
