# Generated by Django 3.2.5 on 2021-09-14 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0027_delete_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('posted_by', models.CharField(default='Posted By', max_length=224)),
                ('job_title', models.CharField(default='Job Title', max_length=224)),
                ('job_description', models.TextField(default='Job Description')),
                ('upload', models.FileField(null=True, upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('vol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer')),
            ],
        ),
    ]
