# Generated by Django 3.2.5 on 2021-09-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0028_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='garbage_collected',
            field=models.IntegerField(null=True),
        ),
    ]
