# Generated by Django 3.2.5 on 2021-09-14 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_alter_home_garbage_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.volunteer'),
        ),
    ]
