# Generated by Django 3.2.5 on 2021-09-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0030_home_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='garbage_collected',
            field=models.IntegerField(default=0),
        ),
    ]
