# Generated by Django 3.2.5 on 2021-09-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_alter_home_garbage_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbagecollecter',
            name='garbage_collected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='garbagecollecter',
            name='volunteers',
            field=models.ManyToManyField(to='my_app.volunteer'),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='collectors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='my_app.volunteer'),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='garbage_collected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopkeeper',
            name='volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='my_app.volunteer'),
        ),
    ]
