# Generated by Django 3.2.5 on 2021-09-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_auto_20210914_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garbagecollecter',
            old_name='collector',
            new_name='picker',
        ),
    ]
