# Generated by Django 3.2.5 on 2021-09-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_collector', to='my_app.volunteer'),
        ),
        migrations.DeleteModel(
            name='Acceptance_s',
        ),
    ]
