# Generated by Django 3.2.5 on 2021-09-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0036_auto_20210915_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeper',
            name='collector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_collector', to='my_app.volunteer'),
        ),
    ]
